[project]
name = "bitty-gpt"
version = "0.1.0"
description = "Lnaguage model Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitty-tokenizer==0.1.4",
    "torch>=2.9.1",
]
